Reformat meteo for Hydrotel
hydrologie/xhydro pull request #185
Opened 2024-08-26 17:20 UTC by RondeauG

### Pull Request Checklist:
- [ ] This PR addresses an already opened issue (for bug fixes / features)
  - This PR fixes #xyz
- [ ] (If applicable) Documentation has been added / updated (for bug fixes / features).
- [ ] (If applicable) Tests have been added.
- [ ] CHANGELOG.rst has been updated (with summary of main changes).
  - [ ] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added.

### What kind of change does this PR introduce?

* ...

### Does this PR introduce a breaking change?

### Other information:

2024-09-04 17:55 UTC, RondeauG commented on src/xhydro/modelling/hydrological_modelling.py
> +            convert_calendar_kwargs = {"target": "standard", "use_cftime": False}
```suggestion
            convert_calendar_kwargs = {"calendar": "standard", "use_cftime": False}
```

2024-09-30 18:29 UTC, essicolo commented on src/xhydro/modelling/hydrological_modelling.py
> +        # Time units in Hydrotel must be exactly "days since 1970-01-01 00:00:00"
Est-ce qu'il y a un risque de recalculer le temps différemment si ds["time"].values est exprimé autrement, par exemple en nanosecondes ou dans un autre format de date comme cftime?

2024-10-01 21:18 UTC, RondeauG commented on src/xhydro/modelling/hydrological_modelling.py
> +        # Time units in Hydrotel must be exactly "days since 1970-01-01 00:00:00"
Les unités sont déjà gérées par `pandas/xarray`, donc ça n'est pas un enjeu. Pour les `cftime`, comme on convertit les calendriers juste avant pour assurer un calendrier standard, ça n'est pas un problème non plus. Cela dit, je vais ajouter un warning si `convert_calendar_missing` crée des NaNs lorsque l'on ajoute les jours manquants.

2024-10-02 16:10 UTC, c-malenfant requested changes

2024-10-02 16:10 UTC, c-malenfant commented on src/xhydro/modelling/hydrological_modelling.py
> +            mask = ~ds.pr.isnull().all(
"all" ou "any"?
Pour Hydrotel (et plusieurs autres modèles), il ne doit y avoir aucun NaN dans les données inputs. Si on met all ici, il faudrait mettre un check plus loin pour s'assurer que toutes les séries de toutes les stations soient complètes.

2024-10-02 17:06 UTC, RondeauG commented on src/xhydro/modelling/hydrological_modelling.py
> +            mask = ~ds.pr.isnull().all(
`all` ici sert à retirer les points de grille qui n'ont aucune données (par exemple, au-dessus de l'océan) quand on passe d'une grille 2D à 1D.

J'ai aussi mis un warning si jamais on doit modifier le calendrier, mais que l'argument `convert_calendar_missing` n'a pas été changé (xarray va mettre des NaN pour les nouvelles dates) --> Ligne 260.

Comme le rôle de cette fonction est de reformater les données, je crois que c'est correct de se limiter à ceci sans traiter les autres données manquantes ? La fonction [`run`](https://github.com/hydrologie/xhydro/blob/b59aa975970683ea167857ad8a038ed6c406683e/src/xhydro/modelling/_hydrotel.py#L234) dans Hydrotel a déjà des arguments pour vérifier s'il y a des données manquantes.

2024-10-02 20:11 UTC, c-malenfant commented on src/xhydro/modelling/hydrological_modelling.py
> +            mask = ~ds.pr.isnull().all(
Excellent, ça répond à ma question.
Je suis d'accord qu'il est préférable de laisser cela entre les mains de l'utilisateur.

2024-10-02 20:12 UTC, c-malenfant approved these changes

2024-10-03 20:18 UTC, essicolo approved these changes

2024-10-04 15:13 UTC, merged