Perturbed indicators
hydrologie/xhydro pull request #54
Opened 2023-12-07 19:59 UTC by RondeauG

### Pull Request Checklist:
- [ ] This PR addresses an already opened issue (for bug fixes / features)
  - This PR fixes #xyz
- [ ] (If applicable) Documentation has been added / updated (for bug fixes / features).
- [ ] (If applicable) Tests have been added.
- [ ] CHANGES.rst has been updated (with summary of main changes).
  - [ ] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added.

### What kind of change does this PR introduce?

* Indicateurs futurs utilisant la technique de pige aléatoire développée pour l'Atlas.

### Does this PR introduce a breaking change?

* No.

### Other information:

2024-01-19 16:21 UTC, RondeauG commented
@c-malenfant Sans nécessairement que tu fasses un review, je crois que cette PR pourrait t'intéresser. Tu peux aussi aller voir le notebook associé: https://xhydro--54.org.readthedocs.build/en/54/notebooks/climate_change.html

2024-02-16 20:14 UTC, c-malenfant requested changes
Excellent. Juste une coquille à vérifier dans le notebook, svp.

2024-02-16 20:14 UTC, c-malenfant commented on docs/notebooks/climate_change.ipynb
Je pense qu'il y a une erreur dans cette section du notebook:

```python
# Categories of agreement for the sign of change. This follows the IPCC Atlas categories.
categories = ["Increase very likely", "Increase likely", "Decrease very likely", "Decrease likely", "No consensus", "No change"]
thresholds = [[0.66, 0.9], [0.66, 0.66], [0.66, 0.1], [0.66, 0.33], [0.66, 0.66], [0.66, 1]]
ops = [[">=", ">="], [">=", ">="], [">=", "<="], [">=", "<="], [">=", "<"], ["<", "<="]]
```
Les thresholds/op me semblent mal correspondre aux catégories.

2024-02-20 15:16 UTC, EdouardMailhot commented on docs/notebooks/climate_change.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #3.    ens_stats_2 = xh.cc.ensemble_stats(delta_dist, statistics)
</pre><p>AttributeError: module 'xclim.ensembles' has no attribute 'robustness_fractions'</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/hydrologie/xhydro/pull/54/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='31'/>

2024-02-22 15:57 UTC, RondeauG commented on docs/notebooks/climate_change.ipynb
En fait c'étaient les catégories de l'Atlas hydroclimatique, mais j'ai changé pour celles de l'Atlas de l'IPCC, avec référence.
Cela dit, les thresholds/op me semblaient bons ?

2024-02-22 15:57 UTC, RondeauG commented on docs/notebooks/climate_change.ipynb
> +{
Done.

2024-02-26 20:32 UTC, Zeitsperre commented
The latest version of `xclim` (v0.48.2) is now compatible with the upcoming version of `xscen` (v0.8.3). This version will be fully compatible with Python3.12.

2024-02-29 16:51 UTC, c-malenfant approved these changes

2024-02-29 16:51 UTC, merged