premières traduction : installation et NB de l'AFL
hydrologie/xhydro pull request #57
Opened 2023-12-11 20:35 UTC by TC-FF

### Pull Request Checklist:
- [ ] This PR addresses an already opened issue (for bug fixes / features)
  - This PR fixes #xyz
- [ ] (If applicable) Documentation has been added / updated (for bug fixes / features).
- [ ] (If applicable) Tests have been added.
- [ ] CHANGES.rst has been updated (with summary of main changes).
  - [ ] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added.

### What kind of change does this PR introduce?

* ...

### Does this PR introduce a breaking change?

### Other information:

2023-12-12 20:14 UTC, Zeitsperre commented on docs/locales/fr/LC_MESSAGES/contributing.po
> +"augmentation de la version)"
```suggestion
"augmentation de la version).**"
```

2023-12-14 20:59 UTC, Zeitsperre reviewed
@TC-FF J'ai pris le choix de ne pas ajouter la documentation autogénérée à partir des docstrings des fonctions/classes, mais veux-tu qu'on les ajoute pour que tu puisses traduire leurs docstrings ? Noter que ça serait de plus en plus ingérable le plus qu'on ajoute du code...

2023-12-14 20:59 UTC, Zeitsperre commented on docs/locales/fr/LC_MESSAGES/authors.po
> +"sebastienlanglois>`_"
Je ne pense pas que c'est nécessaire d'ajouter les traductions pour les phrases/blocs de texte où il n'y a pas des changements. Il va prendre l'originale, non ?

2023-12-14 21:01 UTC, TC-FF commented on docs/locales/fr/LC_MESSAGES/authors.po
> +"sebastienlanglois>`_"
Tout à fait, mais pour la première traduction, j'ay suis allé rapidement avec poeditor, donc en effet, certaines phrases ont été inutilement copiées.

2023-12-15 17:06 UTC, TC-FF commented
@RondeauG @sebastienlanglois @c-malenfant @richardarsenault @Mayetea @EdouardMailhot Première version de la doc en français, je vous tag pour qu'un de vous fasse une relecture de la traduction. Je suis ouvert à des suggestion de traduction pour certains termes techniques (Fork, pull request, package, etc. ) Pour l'instant c'est un mix au feeling entre les suggestion de Deepl, la doc française de GitHub et ce que j'ai vu en ligne... 
Voici le lien pour voir la doc (sinon accessible via un des checks)
https://xhydro--57.org.readthedocs.build/fr/57/

2023-12-15 17:27 UTC, sebastienlanglois commented on docs/locales/fr/LC_MESSAGES/authors.po
> +"sebastienlanglois>`_"
Je suis d'accord de limiter la traduction là où c'est vraiment pertinent (notebooks, fichiers .rst) et ne pas le faire sur les docstrings!

2023-12-15 17:50 UTC, sebastienlanglois requested changes
Il y a quelques petites corrections à faire avant de faire le merge, mais globalement, ça fonctionne très bien!

Aussi, est-ce que le Changelog a été négligé intentionnellement ou non ?

@Zeitsperre Si le fichier original en anglais est modifié (par exemple un notebook déjà existant), est-ce qu'un nouveau fichier .po va écraser l'ancien ou seulement pour les nouveaux msg_str en conservant les anciennes modifications ?

2023-12-15 17:50 UTC, sebastienlanglois commented on docs/locales/fr/LC_MESSAGES/contributing.po
"Implement Features" à traduire

"pour construire la roue" :)

2023-12-15 18:50 UTC, TC-FF commented on docs/locales/fr/LC_MESSAGES/contributing.po
pour construire la roue : Je ne sais pas quoi mettre, on laisse Wheel ?

2023-12-15 18:52 UTC, TC-FF commented on docs/locales/fr/LC_MESSAGES/installation.po
J'irais pour xHydro, c'est hydbirde entre xclim et Xarray ... 
et pour le Changelog c'était intentionel de le laisser inchangé.

2023-12-15 18:57 UTC, Zeitsperre commented on docs/locales/fr/LC_MESSAGES/contributing.po
"Wheel" veut dire quelque-chose en Python. C'est leur mot pour binaire Pythonien. Peut-être c'est mieux de ne pas changer ce mot.

2023-12-15 20:02 UTC, sebastienlanglois commented on docs/locales/fr/LC_MESSAGES/contributing.po
Oui moi aussi je préfère qu'on laisse Wheel

2023-12-15 20:05 UTC, sebastienlanglois approved these changes

2023-12-15 20:13 UTC, Zeitsperre commented on docs/locales/fr/LC_MESSAGES/installation.po
La différence vien du fait que le projet s'appelle `xHydro`, mais le "slug" (le nom de la librairie / comment il est nommé en code et importé) est `xhydro` (pas de majuscule).

2023-12-15 20:14 UTC, Zeitsperre commented on docs/locales/fr/LC_MESSAGES/notebooks/local_frequency_analysis.po
Ton point numéro 4 est adressé, merci!

2023-12-15 20:23 UTC, Zeitsperre commented
> @Zeitsperre Si le fichier original en anglais est modifié (par exemple un notebook déjà existant), est-ce qu'un nouveau fichier .po va écraser l'ancien ou seulement pour les nouveaux msg_str en conservant les anciennes modifications ?

Mon impression, c'est qu'il ne faudrait pas changer la documentation trop pour cette raison. Je ne sais pas pour certain si les changements drastiques (ajouts des lignes, rédactions des phrases) va détruire la traduction, mais mon feeling s'appuie vers oui. Sinon, pourquoi existe-t-il des services comme Transifex pour faire les traductions automatiques ?

2023-12-19 19:20 UTC, merged